const Config = require('./config')
const axios = require('axios');

// Use this file to load some sample insults into our DB
const insults = [
    "Team Fortress 2 is also Free-To-Uninstall",
    "If the body is 70% water how are you 100% salt???",
    "You're the reason the gene pool needs a lifeguard.",
    "I have neither the time, nor the crayons, to explain this to you.",
    "I'm jealous of people that don't know you.",
    "Don't worry guys, I'm a garbage collector. I'm used to carrying trash.",
    "I would insult you but nature did a better job.",
    "Your birth certificate is an apology letter from the condom factory.",
    "Perhaps your strategy should include trying.",
    "I'm not questioning your intelligence, merely denying its existence",
    "I'd tell you to commit suicide, but then you'd have a kill.",
    "Some people get paid to suck, you do it for free. ",
    "You're the human equivalent of a participation award.",
    "I'd tell you to go outside, but you'd just ruin that for everyone else too",
    "With aim like that, I pity whoever has to clean the floor around your toilet",
    "You have worse map awareness than Christopher fucking Columbus.",
    "You must really like that respawn timer",
    "At least your ping score is higher than mine.",
    "You have the situational awareness of a potato",
    "if i wanted to kill myself id jump from your ego to your IQ ",
    "You have the situational awareness of a potato",
    "Your kills are like all Valve franchises, stuck at 2",
    "I'd love to see things from your perspective, but I don't think I could shove my head that far up my ass.",
    "Are you aiming for a pacifist walkthrough?",
    "You know all those times your parents said video games would get you nowhere? They were right.",
    "I hope one day you regain the use of your hands.",
    "Does your ass get jealous of all the shit that comes out of your mouth?",
    "**PROTIP** Your crosshair generally assists you in aiming.",
    "The keys you're looking for are Alt-F4",
    "Your birth certificate is an apology from the condom factory.",
    "Might I suggest you beat the tutorial first",
    "Maybe you should try something more on your level, like rock-paper-scissors.",
    "have you ever had a conversation where the other person wasn't just shaking their head in disappointment?",
    "Everyone who loves you is wrong.",
    "Turning on your monitor would help. ",
    "You are what you eat, and you're a dick.",
    "Maybe you should try a single-player game.",
    "i don't know what gets less hits... your aim or your online dating profile",
    "I bet you're that guy that dies in the tutorial.",
    "WOW! imagine if your parents weren't siblings.",
    "Try playing the game normally, instead of just repeatedly slamming your forehead into the keyboard.",
    "Are your parents siblings?",
    "Even Noah can't carry these animals",
    "You should let your chair play, at least it knows how to support.",
    "You're lagging so hard you're still in 2015",
    "Shut up, you'll never be the man your mother is.",
    "just do exactly the opposite of everything you think and we might have a chance",
    "If your Mom's vagina was a video game it would be rated E for everyone	",
    "You would make a perfect stormtrooper.",
    "If stupidity was a character class, your stats would be legendary.",
    "Is your ass jealous of the amount of shit that just came out of your mouth?",
    "i bet the last time u felt a breast was in a kfc bucket",
    "You must really like spectating your team",
    "It's a joke, not a cock, don't take it so hard.",
    "I didn't know they let Stormtroopers play video games",
    "Feminists get more trigger time than you.",
    " You're the reason they need to put instructions on shampoo bottles.",
    "Tried Uploading this to pornhub...but they don't accept rape",
    "Wait, wait, wait. Let me guess. It was lag, wasn't it?",
    "you camp more than Bear Grylls",
    "I have bowel movements that move faster than your thought process",
    "I have neither the time nor the crayons to explain this to you.",
    "Please be careful to ensure your tears don't get into the electronics.",
    "If life is like a box of chocolates, you're a fucking raisin ",
    "Stormtroopers aim better than you.",
    "A fucking flight of stairs has killed more people than you have",
    "This guy has the map awareness of fucking Christopher Columbus. ",
    "When i die i want you guys to lower my coffin so you can let me down one more time",
    "Try not to trip on your skill level on the way out.",
    "You are why aliens wont talk to us.",
    "Your idea of a comeback is jerking off into a fan",
    "There are vacuum cleaners that suck less than you.",
    "I'm surprised you even managed to get out of bed without hurting yourself",
    "You're worth less than a Steam trading card",
    "Help & Options -> How To Play",
    "Some babies were dropped on their heads but you were clearly thrown at a wall",
    "It's dangerous to use your entire vocabulary in a single sentence!!!",
    "You can start trying any time you like.",
    "Too bad you weren't in control of the Titanic. You would have missed the Iceberg.",
    "You might help your future win-rate by uninstalling.",
    "You need to go back to growing things on Farmville",
    "Maybe you should try something more your speed.. like stopping",
    "I could eat alphabet soup and still shit out a better argument than you.",
    "If it wasn't for gravity you couldn't even hit the fucking ground",
    "If only you could hit an enemy as much as your dad hits you.",
    "404: Skill not found",
    "The keys your looking for are Alt-F4",
    "Im considering playing against you with my eyes closed, cause playing one handed didnt make it any harder.",
    "There are loads of tutorials online that will show you how to setup your mouse properly.",
    "***PROTIP*** use your mouse to look around",
    "I think you dropped a pair of chromosomes right there",
    "Have you considered other hobbies?",
    "I've had jar lids give me a bigger challenge than you.",
    "I hope you're the last person in a human centipede.",
    "Stephen Hawkings probably runs better than your game",
    "If only you could hit an enemy as much as your dad hits you.",
    "only thing u carry is an extra chromosome",
    "You must have been born on a highway, because that's where most accidents happen..",
    "I'm not trash talking, I'm talking to trash",
    "I'm okay with this team. I work in the city as a garbage collector. I'm used to carrying trash.",
    "don't trip on your way into respawn",
    "Shouldn't you be trying to put a round block in a square hole somewhere?",
    " Is your monitor on",
    "If the game was about getting killed, I bet you would be still alive.",
    "Can someone set the bot difficulty at least to medium, please?",
    "I was pro-life until I met you.",
    "hold on im loading my scripts for giving a shit",
    "If I wanted to kill myself I would jump from your ego down to your IQ",
    "You're that one guy that would actually get his dick stuck in a ceiling fan for not following instructions.",
    "I'd rather fuck a bear trap than live a minute of your life",
    "Does your ass ever get jealous of the amount of shit that comes out of your mouth?",
    "you almost didn't die that time",
    "I recommend you keep crying. It's the only thing you're doing right.",
    "Keep rolling your eyes, maybe you'll find a brain back there",
    "How are you this bad at support? Do you work for Comcast?",
    "You must really like spectating your team",
    "are you watching porn or something i swear to god you're playing with one hand",
    "No this isn't Pay-To-Win, all you have to do is pay attention",
    "I'm glad to see you took a break from Cookie Clicker to grace us with your MANY talents",
    "I'm super glad you're enjoying the rich tapestry of art assets and sprites, but some of us are trying to win the fucking game",
    "Hey, give me a shoutout to your 2 Twitch viewers",
    "You're the reason your parents fight",
    "Can you just place your cat on the keyboard and leave? We've a better chance of winning that way. ",
    "If the human body is only 65% water then how are you 100% salty?",
    "I guess the abortion clinic forgot one",
    "Remember that one time when you were good at this game? Me neither.",
    "I bet your club penguin pets killed themselves",
    "**PROTIP** Using a mouse is recommended.",
    "Maybe if you stopped using your keyboard as a doormat you could actually win.",
    "I'm actually a dump truck driver because i carry trash like you all day",
    "Are you constipated? 'cause you ain't doin' shit.",
    "This isn't golf dude.  You don't get a handicap.",
    "This is why people talk about you when you're not around.",
    "Guys, can we put the bots on a higher difficulty?",
    "why turn on the computer if you're just gonna make it depressed",
    "I can't wait till I have dementia so I can forget that ever happened.",
    "To which foundation do I need to donate to help you?",
    "Your asshole must be jealous of all the shit that comes out of your mouth.",
    "If you keep crying, we're going to need to build another Ark.",
    "Be honest, are you just a cat swatting at the keyboard? ",
    "You know that if you plug the screen in you can actually see the enemies.",
    "i'm just impressed you're still trying to play with a trackball",
    "You must be so confused about the tiny people in your computer screen.",
    "You couldn't be more inbred if you were in a fucking sandwich.",
    "You should eat some makeup so you can at least be pretty on the inside.",
    "aww, you're just like Jesus, always respawning and never hurting anyone :)",
    "How many tries did it take for you to click the install button?",
    "A law prohibiting you from breeding would be justified but unnecessary",
    "All of these flavors and you choose to be salty",
    "Can't hear you from the bottom of the scoreboard",
    "Achievement Unlocked:  More Time Dead Than Alive",
    "You failed, just like your dad's condom",
    "I'd call you a piece of shit but that at least has use as fertilizer",
    "Your years of practice on easy bots clearly paid off.",
    "Can you please check if your mouse is plugged in?",
    "You couldn't pour water out of a boot if the instructions were on the sole.",
    "When your parents said shoot for the stars, this is not what they meant.",
    "With all these flavors why do you choose to be salty?",
    "I'm pretty sure the only thing you can turn on is your laptop.",
    "What's the difference between you and a bench? The bench can actually support an entire team.",
    "I see somebody went to the Stormtrooper school of marksmanship. ",
    "You're dying so much that you could replace Sean Bean.",
    "You can start trying now.",
    "I could eat a bowl of alphabet soup and shit out a smarter statement than that.",
    "A woman at a urinal has better spray control than you",
    "Do you lose when you play against yourself?",
    "I cant hear you at the bottom of the scoreboard",
    "It's a joke, not a cock, don't take it so hard",
    "Oops, I must have chosen easy bots by accident",
    "If you want to hear about mistakes, ask your parents.",
    "you could season a meal with all that salt from your tears",
    "Does your mouse have kickback when you shoot?",
    "You deserve a high five, to the face, with a chair",
    "I think you'd have more fun playing something you were good at.",
    "Children with cancer take losing better than you do.",
    "Does your ass ever get jealous of the amount of shit that comes out of your mouth",
    "I'd suggest you to uninstall the game but I bet it's too complex for you",
    "I understand blaming the lag... between your brain and reflexes.",
    "The only thing you are carrying is an extra chromosome",
    "Is your huge death count compensating for something?",
    "I bet if you would go afk, you would play better",
    "There's a good game for you to practice. It's called Cookie Clicker.",
    "You might just create another dead sea with all your tears.",
    "Have you tried turning your brain off and on again?",
    "Not even Atlas can carry this Team",
    "Yes, we know, you have a penis. Please remove it from the keyboard and play. ",
    "I've seen you die more times than I've seen my dad in my whole life.",
    "I'd tell you to blow me but you've been sucking dick all game",
    "Go play Lemmings, at least you'll be able to kill something.",
    "Go down to the nearest drugstore and buy a little thing called viagra. It will help you go fuck yourself.",
    "Even a stormtrooper has a better aim than you",
    "You should commit suicide. That way you'd have at least one kill.",
    "Oh wait, this is not a bot game?",
    "Don't shoot yourself! Not because I'd miss you, because you'd miss you",
    "Im sure that extra chromosome helps you out with something but it sure as fuck isnt this",
    "The only problem with your PC is that thing between your keyboard and your chair",
    "I wish my HIV-Test would be as negative as your score ",
    "you couldn't be more inbred even if you were in a fucking sandwich",
    "Hey you got something added to your score. Wait... that's just another death.",
    "I'm trying to see this from your perspective, but I can't seem to get my head that far up my own ass.",
    "Correct! I am a tool, because unlike you, I'm actually useful.",
    "It's just a joke not a dick, don't take it so hard.",
    "The guy who played CSGO with a wheel is better than you",
    "You are like Forrest Gump but without the running thing.",
    "You're about as useful as Anne Frank's drum kit.",
    "You should make a team and call it 'soup kitchen' cause you're feeding everyone",
    "How'd you get through the tutorial?",
    "Isn't your time running out on the library computer?",
    "Remember that it's better to try and fail than to not try at all, so don't be afraid to start trying any time now",
    "I'd tell you to kill yourself, but I'm pretty sure you'd miss.",
    "Let's just let natural selection take it's course",
    "95% of lag occurs between the player and the computer",
    "Feed any more and you'll end world hunger.",
    "I bet you can't see the screen with all your tears",
    "It was just a joke not a dick, don't take it so hard.",
    "I didn't know toasters could run this game",
    "Imagine what your life would be if your parents weren't siblings.",
    "Well I would agree with you but then we'd both be wrong",
    "The way you're feeding, you could feed Africa for a year.",
    "I think you should press the power button in order to contribute to the game.",
    "A million years of evolution and we get you.",
    "You probably get your insults on CS:GO from a shittalk generator",
    "If I wanted to listen to an asshole, I'd fart",
    "Maybe Hello Kitty Island Adventure is more around your skill level",
    "Your face looks like it was made by Bethesda",
    "Your family tree is a cactus, because everybody on it is a prick.",
    "The only thing you've killed this game is my faith in you.",
    "If I had 2 bullets and I was in a room with Bieber, Hitler, and you, I'd shoot myself twice.",
    "even the steam support is more useful than you",
    "at least you could become a stormtrooper",
    "Your aim is so poor Bono is holding a charity concert for it.",
    "I don't lift, but I sure do carry.",
    "You are as useless as a white crayon",
    "Ethiopia could eat for a month the way you are feeding.",
    "Would you like some fries with that salt?",
    "You're the reason your dad drinks",
    "You're supposed to be farming gold, not chromosomes.",
    "The game wants to uninstall you.",
    "Your reaction time is as fast as coastal erosion. ",
    "I would ask if you were new, but that would imply you can actually get better",
    "I'd tell you to kill yourself, but chances are you'd fuck that up too",
    "Atleast you got through the tutorial",
    "How many tries did it take for you to click on the button that launches the game?",
    "ethiopia could eat a year the way you are feeding ",
    "Are you collecting bullets?",
    "I guess my team is sponsored by the Make-A-Wish foundation...",
    "Auto-sniper just means it's semi-automatic. You stil have to aim.",
    "Two wrongs don't make a right, take your parents as an example.",
    "Mentally challenged people don't want to be referred as 'Retarded' becuase they don't want to be compared with you.",
    "If you want to reduce the number of times you lose, you could try uninstalling",
    "Letting you live was medical malpractice",
    "I'm a plumber and even I can't handle your shit.",
    "Your existance is proof people don't know how to pull out.",
    "Are you playing on pacifist mode?",
    "If this was pay-to-win, you'd go bankrupt before you got your first kill.",
    "Access the cheat menu with ALT + F4",
    "At least buy your jungler some marshmallows if he's going to be camping so much",
    "Who set the bots to passive?",
    "Believe in yourself, because the rest of us think you're an idiot.",
    "That crosshair is for aiming at enemies, you know.",
    "I'm surprised that you were able hit the 'Install' button",
    "PROTIP: Knowing when to quit is a useful skill.",
    "If we learn from our mistakes, your parents must be geniuses now",
    "All the flavors in the world....and you choose to be fucking salty",
    "Don't worry guys, I am a trash man IRL. I am used to carry garbage like you",
    "Your aim is so poor that people held a fundraiser for it",
    "I'm surprised you even hit the power button on your computer.",
    "I've seen better reflexes from Bethesda NPCs",
    "I don't have the time or the crayons to explain this to you.",
    "Next round, you should try looking at the monitor.",
    "Just because you can act like a dumbass doesn't mean you should.",
    "Everyone who has ever loved you was wrong",
    "Friendly fire was invented because of you.",
    "My cat sleeping on the keyboard would do a better job",
    "I would mentally duel with you, but I can see you're unarmed",
    "Do you want some fries with that salt",
    "Does your owner know you're running on the keyboard?",
    "Fighting on the internet is like participating in the paralympics. Even if you win, you're still retarded.",
    "Remember, riding dick is not a mode of transportation.",
    "I was going to make a joke about your kills but I couldn't find any.",
    "I noticed your sister got all the good genes from the family.",
    "My abacus has more processing power than you.",
    "Whoever told you to just be yourself couldn't have given you worse advice",
    "Are you worried about the moral consequences of killing someone in a game?",
    "People like you demonstrate why Single Player mode should be mandatory.",
    "At least your immune system tries to stop you from dying.",
    "That respawn timer might be one of your best friends right? ",
    "Your aim is proof that excessive masturbation causes blindness",
    "I didn't realize 'Moving Target Dummy' was a selectable character.",
    "I've had more engaging arguments with my dog",
    "Your existence is the reason for scientists to rethink the plausibility of evolution.",
    "Maybe it's time to upgrade from dial up.",
    "Even the game's client-side prediction has no idea what you're trying to do.",
    "Try switching your router off, that might help.",
    "You are the reason I have to doubt evolution and natural selection",
    "Your aim is so shit you couldn't hit the ground if you fell",
    "press alt-f4 to help the team",
    "'Three-second burst' should be your rate-of-fire, not your life expectancy",
    "Unplug the Ethernet cable. That gets rid of the lag.",
    "Maybe if you try to miss, you might hit something!",
    "If you stopped jerking off, maybe the blood would go to your brain instead.",
    " 	 I don't have the time or the crayons to explain this to you.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "I almost mistook you for an actual threat there.",
    "Not even Noah carried this many animals",
    "You could end world hunger with how much you feed",
    "Don't worry, everybody was new once. You just... stayed.. new, somehow...",
    "I would call you AIDS but at least AIDS gets kills",
    "The way you're feeding, you could end world hunger.",
    "Play with a blindfold on, at least you'll have a valid reason for missing all those shots.",
    "'Twitch Plays TF2' would be more useful than you.",
    "Why don't you check between your chair and your keyboard for the problem?",
    "The only keys that's worth hitting, is that power button on your computer.",
    "You probably think the light in the refrigerator never turns off.",
    "Two wrongs don't make a right, take your parents for instance",
    "It's sad that your IQ matches your shoe size.",
    "At least your K/D is better than your GPA.",
    "You'd have made an excellent Stormtrooper",
    "You know what man, blind gamers deserve a chance too. I support you.",
    "Good job keeping your learning curve perfectly horizontal. ",
    "John Lennon is better at dodging bullets than you",
    "I believed in the good and potential of humanity. And then you came along.",
    "Did Marvel buy the rights to your mouse?  Because you can't seem to actually kill anybody off.",
    "Like the Dead Sea wasn't salty enough.",
    "stop hogging all the deaths",
    "Only thing you carry is an extra chromosome.",
    "You're the type of person who would miss at point blank range with a flamethrower.",
    "I've been to daycares more threatening than you",
    "You could play in an empty server and still somehow manage to lose CTF.",
    "Warmup ended several rounds ago.",
    "If I wanted to get yelled at by folks like you, I would go to the daycare. ",
    "You're just like a dog, all bark and unable to play video games.",
    "I didn't know dying was a special ability.",
    "I see you gained a new hobby, Collecting Bullets.",
    "Your mind is just as stable as your internet connection.",
    "Your aim is so bad you couldn't hit water if you fell out of a boat",
    "Blink twice if your skill is being held hostage.",
    "You know this isn't turn based combat right? When they shoot at you feel free to shoot back.",
    "Congress works better than you.",
    "You're the reason abortion was legalized",
    "You make stormtroopers look good.",
    "Stairs has killed more people than you have. ",
    "30 millon sperm and you swam the fastest?",
    "Did you empty your ammo for warning shots?",
    "I normally don't argue with children but I'll make an exception for you.",
    "Try doing hand stands sometimes. I think your brain needs more blood.",
    "If you were a real terrorist, the world would be a much safer place.",
    "I'd agree with you, but then we'd both be wrong.",
    "You know your team is trying to win right?",
    "You have some big balls on you. Too bad they belong to the guy fucking you from behind. ",
    "How the fuck were you the fastest sperm???!",
    "Players like you are why Easy mode is a difficulty option.",
    "Perhaps you should try something more innovative, like playing.",
    "If you ever win a match screencap and send to the church. Pretty sure that'll count as a miracle.",
    "I think you should just go afk. You'd get better results.",
    "Even Gandhi is jealous of your pacifist playstyle.",
    "Arguing on the internet is like competing in the special Olympics. Even if you win, you are still retarded.",
    "Team Fortress 2 is also free to unistall",
    "Move your sisters head, I'm gonna kick you in the dick",
    "Even a common cold has a higher kill count than your aim",
    "Not even Noah could carry these animals.",
    "You're about as useful as a snowshovel in Hawaii.",
    "Stephen Hawking has better hand-eye coordination than you.",
    "God ran out of clay, so he slapped a bunch of dog shit together to make you",
    "I'd tell you where the uninstall button is but you'd miss that one too",
    "Does your mouse have recoil or something?",
    "Don't beat yourself up. We already did that for you.",
    "I bet you have alot of participation awards...",
    "Were you always this shitty or you're trying really hard today?",
    "You didn't make a mistake. Your parents did.",
    "Why don't you slip into something more comefortable? Like a coma?",
    "You're lucky your dad's dick had better aim than you. ",
    "Your best Kill of the Day: my time",
    "You must have been born on a highway, because that's where most accidents happen",
    "Out of any animal you identify with, you chose a bitch.",
    "I don't know what your problem is, but I bet its hard to pronounce ",
    "You'd have the top score if this was golf",
    "You could win an oscar for how sad your life is.",
    "I see your hobbies include lag, friendly fire and caps lock. Good for you.",
    "Good job, now try that on the other team!",
    "Rick Astley gave you up 'cause you let him down.",
    "It'd be an insult to compare a stormtrooper to you. At least they know what they're trying to shoot at.",
    "Your mother should have swallowed you",
    "I'm Sorry I Can't Hear you From the Bottom of the Scoreboard",
    "How did you ever get through the tutorial level?",
    "You're the MVP of the other team",
    "Just because you have the ability to click play doesn't mean you should.",
    "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
    "I've seen more support for North Korea than I've seen all game from you.",
    "I wonder if you last as long in bed as you do in this game.  I'd ask your girlfriend, but hands can't talk.",
    "Most people missed out on the lottery, you missed out on the gene pool.",
    "I bet you would blame it on the lag at a LAN party too.",
    "your birth certificate came with an apology letter from condom factory.",
    "You are the reason aliens wont talk to us",
    "Your kill list is shorter than a list of french war heroes ",
    "Stormtroopers hit their targets more than you.",
    "Maybe you should just stick to playing singleplayer games.",
    "The way you feed, you could stop world hunger.",
    "Your family tree is a cactus because everybody on it is a prick.",
    "You remind me of the last batch of scrambled eggs I made: beaten, over-salted, and burned.",
    "It is dangerous to use your whole vocabulary in one sentence.",
    "You are proof enough that guns do not kill people.",
    "You are the MVP of the other team.",
    "I'm still not convinved God exists, but if he does you prove he has a sense of humor.",
    "Just as a heads up Steam has a 2 hour, no questions asked refund policy. I suggest you take advantage of it while you can. ",
    "Only thing you're carrying is an extra chromosome.",
    "Why are you still here? I thought trash day was yesterday.",
    "Stevie Wonder can see how shit you are",
    "Now I know why nearly every game has arrows pointing to the objective. They were all for you.",
    "I wonder if the sperm that had the skills is watching you from your mom's mattress.",
    "If your dad's aim was as good as yours we wouldn't be talking right now.",
    "If skills were a disease, you'll be immune to it.",
    "If we were playing a game in which the objective were to shoot walls, you would still lose.",
    "I think I broke the weightlifting record by carrying this team.",
    "It seems you and the kill cam have become well acquainted",
    "Do you ever wonder what life would be like if you'd had enough oxygen at birth?",
    "The killcam ran out of film thanks to you.",
    "Congratulations! You've made the enemy team's highlight reel!",
    "I'd call your aim cancer, but at least cancer can kill people.",
    "Calling you a retard is an insult to the mentally challenged",
    "It's quick, it's easy, and it's free: Trying.",
    "Embarrassing. I've heard better shittalking from a goddamn crowdsourced generator",
    "I'm sure your bodypillow is very proud of you.",
    "Don't you love nature, despite what it did to you?",
    "I would insult your IQ, but the concept of negative numbers would boggle your mind.",
    "I'd call you cancer, but at least cancer kills.",
    "Did your parents try to get a refund?",
    "Maybe God made you a bit too special.",
    "I would ask you how old you are but I know you can't count that high.",
    "Playing with you is like the Shawshank Redemption, only with more tunneling through shit and no fucking redemption.",
    "I'd tell you to go play in traffic, but you'd probably suck at that too.",
    "I`d call you cancer, but cancer actually gets kills",
    "When I die I want you guys to lower my coffin so you can let me down one last time.",
    "The only thing you carry is an extra chromosome",
    "Your aim is so poor, even African countries feel the need to donate to you.",
    "I bet he came here because Minecraft was too hard",
    "I bet you blame the lag even when you're playing with bots.",
    "I have neither the time, nor the crayons, to explain this to you..",
    "You are a living contradiction to evolution.",
    "Pro Tip: You can uninstall any game you play.",
    "Do your parents cry every day or just on the days they realize they didn't get the abortion?",
    "You paid $1500 just to get destroyed in 4k. Good Investment.",
    "Imagine going through 9 months of pregnancy to give birth to a child who doesn't push the payload.",
    "If your face was a Counter Strike map, it would be de_formed.",
    "You couldn't hit water if you fell out of a boat.",
    "Your parents aren't the only ones who regret knowing you",
    "If ignorance is bliss you must be the happiest person alive.",
    "I'm sorry, you'll have to be louder- sound doesn't travel all the way up the scoreboard.",
    "You're like an onion. On the outside you're shit, but peel away a layer and underneath is another layer of shit",
    "With that aim, I'm impressed you could even hit the queue button.",
    "You can turn on your monitor now.",
    "My shoes have more support than you've given me.",
    "Did you skip the tutorial?",
    "You  have an inferiority complex, and it's completely justified",
    "Do you lose when you play against yourself too?",
    "If I wanted to kill myself I'd jump from your ego down to your rank",
    "This is why doctors advocate regular masturbation, to keep fuck ups like you from being conceived. ",
    "Are you AFK? Good, we finally have a chance of winning.",
    "I'd say you suck, but that would mean you have some value",
    "Your aim is like your crush, never gonna hit it",
    "I would tell you to shoot yourself, but you'd miss.",
    "You're a prime example of why the gene pool needs a whole lot of bleach",
    "please look at the screen when you are playing",
    "Hitler knew when to kill-himself. Why can't you do the same?",
    "video games bring new experiences and right now I'm experiencing what it's like to be a special needs caretaker",
    "If you were any dumber I would have to water you twice a day",
    "When i die i want you guys to lower my coffin so for once you can carry me. ",
    "Even Atlas couldn't carry you",
    "There are about 37 trillion cells working together in your body right now, and you are disappointing every single one of them.",
    "I feel like you are the type of person to go negative against bots",
    "I guess the condom broke and the coat hanger wasn't long enough.",
    "Were you born on a freeway? Because that's where most accidents happen.",
    "When you go to a family reunion, who brings the condoms?",
    "it was a joke, not a dick, don't take it so hard..",
    "please look at the screen when you are playing",
    "Do you know you need a mouse to play, right?",
    "I must be Noah's Ark. I'm carrying a bunch of fucking animals",
    "You're the reason negatives numbers exist",
    "Imagine that someone was pregnant for nine months, gave birth, and their child doesn't even play the fucking objective.",
    "Could you please play with both hands?",
    "Your K/D would vastly improve if you killed yourself",
    "Of all these different flavours, you chose to be salty.",
    "You're as useful as a white crayon",
    "I'd give a penny for your thoughts, but I don't want to overspend.",
    "You might as well start hacking, that way you could finally achieve something; a ban.",
    "You're baiting so hard you could probably catch a fucking shark",
    "Do you believe in God ? cause he dosn't believe in you.",
    "The only thing you carry is aids",
    "You don't have to worry about friends talking shit behind your back, seeing you have none.",
    "So many flavors to choose from, and yet you choose salt",
    "If I got a dollar every time you missed a shot i could buy you the glasses you so desperately need.",
    "you're topping the scoreboard in chromosome count",
    "I'd call you cancer, but at least cancer gets kills.",
    "You could be the only person in the game and still manage to die.",
    "You are the reason why abortion is legal.",
    "At least terminal cancer gets kills.",
    "You should give that extra chromosome back, it's not nice to steal",
    "You probably would've shot the kid instead of Harambe ",
    "Can a medic take a look at my back? It hurts from carrying this team.",
    "imagine going through 9 months of pregnancy to give birth to a child who doesn't push the fucking payload.",
    "Ah yes, the Dead Sea, the second saltiest thing on Earth next to your bitch ass.",
    "I can't carry you with all those extra chromosomes weighing you down.",
    "I doubt you can even count to your score.",
    "Have you considered pointing that gun the other way around?",
    "I wish we'd met years ago, I would have repressed the memory by now",
    "You have as many kills as you have brain cells.",
    "Imagine going through 9 months of pregnancy just to give birth to a child who doesn't push the fucking payload",
    "I'd agree with you, but then we'd both be wrong",
    "PROTIP: you have a second hand for the keyboard",
    "If you'd been the terrorist piloting the jet in 9/11, the towers would probably still be there",
    "This team could lose at Farmville. ",
    "I need an apology letter. Can I borrow your birth certificate?",
    "does your ass ever get jealous of all the shit that comes out of your mouth?",
    "I was anti-abortion before I started this match but now I'm reconsidering.",
    "if you open up enough crates, one might contain the chromosome you left inside your mom. ",
    "Did you know sharks only kill 5 people each year? Looks like you got some competition",
    "im gonna be able to deadlift 400 pounds by the time im done carrying you",
    "I'd call your aim cancer, but cancer kills",
    "With a score as low as that, you must be amazing at golf.",
    "Kirby must be jealous with how much you suck.",
    "Guys, how about you fix some handles to yourselves, so it'll be easier for me to carry you?",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You should've quit while you were ahead. Which was before you installed.",
    "I'd say your aim is cancer, but cancer actually kills",
    "You sound like you roofy yourself at gay bars",
    "At least you could survive the abortion.",
    "I've avoided smoking my entire life to prevent cancer, but with a play like that it seems I've missed out on cigars for nothing.",
    "Mistakes were made, the worst one was by your parents.",
    "I'd call you cancer, but it kills.",
    "You are a walking condom advertisment.",
    "I would call you a cunt, but a cunt has a use.",
    "Why is there an enemy team when I have my own shit teammates to deal with.",
    "I'd tell you to just end it and shoot yourself, but you'd probably miss.",
    "I've never touched a cigarette. I feel a sense of regret for not doing it, because you gave me cancer anyway.",
    " Your parents deserve more than this.",
    "I'd tell you to kill yourself but you probably couldn't even manage that",
    "Christopher Columbus has better map awareness than you",
    "You're living testament to the idea that people only use 10% of their brains",
    "When I die, I'd like you to lower my coffin, so you can let me down one last time. ",
    "I'd call all of you cancer, but at LEAST cancer kills.",
    "You guys answered the age-old question of whether God could create a team of people so dense that even he could not carry them",
    "You're more fucked than a Ditto in day-care. ",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "Stupid people can believe in anything, so you can believe in yourself",
    "If you worked at a zoo, Harambe would still be alive.",
    "You couldn't even hit puberty.",
    "I'd say you're cancer but at least cancer can kill people",
    "I'd call my team cancer, but at least cancer kills.",
    "Please tell me you're actually a 'Twitch Plays' script",
    "I know you're trying your best, but I wish your best was actually trying.",
    "Your birth certificate was an apology from the condom company.",
    "I'd ask you to shoot yourself, but you'd probably still miss.",
    "You're why I'm pro-choice.",
    " 	 I bet you guys are going to single-handedly keep the porn industry alive for the next 30 years the way you're fucking us.",
    "Your parents must have been disappointed with the one-child policy",
    "Michael J. Fox would be a better sniper main than you",
    "It's not that I hate you, you just don't deserve respect in the first place.",
    "I bet you guys are going to single-handedly keep the porn industry alive for the next 30 years.",
    "Comcast gives better support than you.",
    "You're living proof that God has a sense of humour",
    "I'd trade you for a park bench, at least it could support the team",
    "If I wanted an excuse, I would've asked your mother why you werent aborted.",
    "I would have been you for Halloween, but I couldn't fit 7 dicks in my mouth",
    "The only thing that will ever fuck you, is life. ",
    "Your Tinder profile has seen more lefts than a Nascar track",
    "Team Fortress2 is also Free-To-Uninstall",
    "I wish you took the bullet instead of Harambe.",
    "You're the type of player to get 3rd place in a 1v1 match",
    "If you listen closely, you can actually hear the salt crystals forming",
    "Roman soldiers were once paid in salt. These days people like you are giving it out for free.",
    "I would unplug your life support to charge my phone.",
    "I used to think everyone had the potential to be great, then I discovered you.",
    "I'd try to see things from your point of view but I couldn't get my head that far up my ass.",
    "You'd struggle to pour water out of a boot if the instructions were written on the heel!",
    "I'd call you cancer, but cancer gets kills.",
    "Fuck yourself. You'll finally get some pussy that way. ",
    "Your existence is the best argument against intelligent design.",
    "I'd call you a tool, but that would imply you were useful in at least one way.",
    "You say that as if I value your opinion.",
    "At least I have a father and not 10 suspects.",
    "You're as useful as Stephen Hawking's home gym",
    "If I were to insult you, it'd be animal abuse",
    "You bring down the property value just being here.",
    "Your parents need to get a very late term abortion",
    "You look like someone pressed the randomize button in the Oblivion character creator.",
    "You couldn't pour water out of a boot with instructions on the heel",
    "Remember when your mother told you to be yourself? Please don't do that.",
    "This game has a wide variety of playable characters and playstyles, and I'd appreciate it if you'd learn one.",
    "The only thing you can throw is the match",
    "Two men walk into a bar. You walk into a fucking pole.",
    "Legend has it that the number 0 was first invented after scientists calculated your chance of doing something useful.",
    "You couldn't even support a drug addiction",
    "Wait, don't go. I still need more salt on my food.",
    "Which is lower, your score or your IQ?",
    "When I die I want you to to lower me in my grave so you can let me down one more time.",
    "Each time you spend time typing, we actually do better.",
    "I regret not smoking my entire life, because watching you still gave me cancer.",
    "I'd call you cancer, but at least cancer kills people.",
    "With that poor aim, im surprised your dad figured out where to stick it in",
    "You're the type of person to try and shoot up a school with a nerf gun",
    "If I had a dollar for every time you missed a shot I could buy you the glasses you so desperately need.",
    "If you got cancer, I would feel bad for the cancer.",
    "You're an inspiration for birth control.",
    "If I wanted to kill myself, I would climb up to your ego and jump down to your IQ level",
    "I used to be an athiest but only divine intervention could create something as miserable as you.",
    "I would say this team is cancer, but at least cancer gets kills",
    "I've seen obese Mexican food vendors push carts better than this team.",
    "Your skill is like John Cena, nobody can see it",
    "You are probably the only person that will miss with an aimbot.",
    "If you were any more inbred you'd be a sandwich",
    "Save your breath, you'll need to to blow up your girlfriend later.",
    "Really wish I could aim this gun at myself instead of the enemy team.",
    "When I die, I want you to put my casket into my grave, so that you can let me down one last time.",
    "Surprised you got past the tutorial honestly",
    "If there would be a loser contest you'd win a second place. Because you are a loser.",
    "Imagine going through 9 months of pregnancy only to give birth to someone who decides to be the fucking fourth spy on the team.",
    "If I wanted to kill myself I'd jump from your ego down to your IQ.",
    "You couldn't pour water out of a boot if the instructions were on the heel",
    "I'd call you a cunt, but you lack the warmth or the depth. ",
    "Imagine going through a nine month pregnancy only to give birth to someone who can't push the fucking cart.",
    "If we win this game, you only need one more miracle to become a saint.",
    "Imagine going through 9 months of pregnancy to give birth to a child who doesn't do the fucking objective.",
    "ergkirhrjrl;asewi    shit, sorry, my cat walked on my keyboard and somehow it still played better than you.",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "Iridium is known to be the second densest thing on the planet. Congrats on being more dense than Iridium.",
    "We should call this team 'The Stormtroopers' cause none of you can fucking hit anything.",
    "I'd call you cancer but at least cancer can kill things",
    "Harambe didn't die for this.",
    "your hand to eye coordination is more broken than TF2's matchmaking system",
    "Aiming can increase your accuracy.",
    "Team Fortress 2 is also Free-To-Uninstall,",
    "Stephen Hawking knows the secrets of the universe; but can't figure out how people as stupid as you put on shoes this morning.",
    "When scientists finally find what the object at the centre of our galaxy, it's going to be your dense fucking head",
    "I'd insult you, but my mother told me not to insult the handicapped. ",
    "I'd rather have a single Stormtrooper than any of these fucking Snipers.",
    "I'm a support main but I can't heal this team's cancer.",
    "The only game you could get a high score in is golf.",
    "How about you stop carrying the other team?",
    "If I wanted you to open your mouth I'd jingle my zipper",
    "I would tell you a joke, but your entire existance makes a better job at that than me.",
    "You're the reason they need to put instructions on Bleach bottles ",
    "Tip : Turn on your monitor to see what's ahead of you!",
    "I'd say you're cancer, but at least cancer kills.",
    "I'd make a joke, but you're already here",
    "You need a higher aspiration in life than just being a giant fucking failure, buddy.",
    "Calling you a retard is a compliment in comparison to how stupid you actually are.",
    "31.5 N, 35,5 E, the coordinates of the Dead Sea, the saltiest place on earth next to your bitch ass.",
    "You can mine salt from the ground, or you can dry seawater. I don't have to do either, I've got you.",
    "Suicide is always an option.",
    "I had no expectations for you and yet you still managed to disappoint. Bravo.",
    "Your mind is like a steel trap. Rusty and difficult to operate with years of disuse.",
    "I think Steam Support do better job than you did",
    "You remind me of the son I never wanted",
    "Eat your veggies kids, that's how I got strong enough to carry you all",
    "If you were to shoot yourself, your K/D ratio would improve by 100%.",
    "If you were the person controlling the plane, you wouldve missed the Twin Towers.",
    "players like you should come with a handicap sticker",
    "You look like your face was on fire and someone tried to put it out with a fork",
    "Wow, this game should really be R-rated. I'm looking at the killfeed and all it shows is our team getting fucked. ",
    "I'd call you an ape, but that'd give them more of a reason to shoot Harambe again.",
    "If you made as many good plays as made excuses, you'd have won EVO by now.",
    "It must be difficult for you, exhausting your entire vocabulary in one sentence.",
    "At least your ping is higher than your death count.",
    "You're such a pussy that fucking you wouldn't be gay.",
    "A fortune teller told me that I was going to kill a vegetable today, I guess that time is now...",
    "You weren't worth the sex that made you. ",
    "Imagine waiting 9 months to give birth, and it's you.",
    "By the time this match ends you'll have as many deaths as chromosomes. ",
    "You must have been born on a highway because that's where most accidents happen.",
    "I would call you a cunt, but you lack the warmth or the depth.",
    "Imagine being pregnant for nine months only to give birth to a fucking idiot who thinks recycling this joke is a good idea.",
    "The way you're feeding, Africa may finally have a chance.",
    "I'd insult your mother, but I'd hurt your sister's feelings.",
    "I'm not saying you're useless, but I'd unplug your router to charge my phone. ",
    "If laughter is the best medicine, your face must be curing the world.",
    "With an aim like that, I'm surprised you were able to turn your PC on.",
    "You're the reason why no religion has a god that stays on Earth.",
    "I'd say your aim is cancer, but cancer actually kills people.",
    "They should put you on pamphlets as a warning to teenagers.",
    "Your mother should've spent the money on an abortion rather than the booze she drank during the pregnancy.",
    "I've seen better reflexes from Polio sufferers.",
    "Stephen Hawking did great with his disability. Why can't you?",
    "What you lack in brain cells, you make up for in chromosome count.",
    " Why don't you slip into something more comfortable -- like a coma",
    "Christ died for your sins and this is how you repay him?",
    "Its a shame you werent the pilot of 9/11, you would have missed the building.",
    "Why don't you slip into something more comfortable...like a coma.",
    "I would call you cancer, but cancer actually kills people.",
    "just because it's on the scoreboard, it doesn't mean dying gets you points",
    "If you're going to be two-faced, at least make one of them pretty.",
    "I would insult you, but my parents always told me not to abuse the profoundly handicapped.",
    "You lost the game for us? Don't worry, everyone makes mistakes, even God does, we have you to show for it!",
    "I'm pretty sure you've typed more sentences than landed shots.",
    "Team Fortress  is also Free-To-Uninstall",
    "Could you imagine what it would have been like if you had more oxygen at birth",
    "Just fucking throw your mouse at your screen, that'll be the first shot you hit. You know what? You'll just miss that too.",
    "I sometimes contemplate suicide, but then who would be around to tell you how terrible you are.",
    "You should try your luck at russian roulette, at least you might kill something",
    "It's a joke, not a cock. Stop taking it hard.",
    "You should turn the game off. Just walk outside and find the nearest tree, then apologise to it for wasting so much oxygen.",
    "My vacuum cleaner is sucking less than you.",
    "If ugliness was measured in bricks, you would make the great wall of china.",
    "Kennedy dodges bullets better than you do.",
    "I've seen better reflexes from a melting stick of butter down a hill.",
    "I suggest turning your monitor on for improved gaming performance.",
    "Shhh, you're 12, you still need permision to use club penguin.",
    "I see, the reason you don't push the payload is that even it can't carry you if you sit on it.",
    "It's kinda sad watching you attempt to fit your entire vocabulary into one sentence.",
    "I understand your frustration. It's really hard to see what you're doing through all your tears.",
    "I've seen blind paraplegics suffering from pancreatic cancer fire a gun more accurately.",
    "You're the kind of guy who could lose to the maze on the back of a cereal box.",
    "Your aim is so poor Obama made a plan for it.",
    "You're a perfect example of why coathangers aren't strong enough.",
    "Imagine how much better you would be if your monitor was on.",
    "I've had more engaging arguments with my cat",
    "Weird, I didn't know they let bots run loose in public games?",
    "Holy shit! You're not just useless, you're harmless too!",
    "I bet your Birth Certificate is just a letter of apology from Planned Parenthood.",
    "Give your parents my sympathy. I know it's hard raising an autistic child.",
    "Abraham Lincoln can dodge bullets better than you.",
    "Your mother is so ugly people break into your house just to close the curtains",
    "Maybe if you spent as much effort on the game as do bitching, you might actually kill something other than my will to live.",
    "If I wanted to kill myself, I would climb up to your ego, and jump down to your IQ level.",
    "Yesterday I stepped on a pile of dogshit, It reminded me of you.",
    "The Earth is 75% salt water, still less than the amount coming from your mouth",
    "You make the dead sea seem like spring water",
    "I'm jealous of all the people who have never met you.",
    "What's the biggest difference between you and Hitler? At least Hitler managed to kill himself.",
    "The ocean must be jealous from the amount of salt you hold.",
    "My dick is the size of your ego.",
    "I think you need to talk to your doctor about Type 2 Diabetes. You seem to be consuming a lot of salt.",
    "Does your ass get jealous of the shit that comes out of your mouth?",
    "You can't upload footage of this match to PornHub, because they don't allow rape.",
    "I'm jealous of people that didnt know you.",
    "I need to hire a plumber... I flush and I flush and I flush, but you're still here.",
    "I heard you took an IQ test but the results said 'Negative.'",
    "You should have been swallowed ",
    "The only thing that you can hit is rock-bottom.",
    "Can you please start using your mouse instead of your controller?",
    "It's incredible how you can bring so many people so much joy just by leaving the game!",
    "I love a good sale, but ain't nobody buying your bullshit.",
    "If I gave you a penny for your thoughts how much change would I get back?",
    "Does your brother know you're playing while he's AFK?",
    "Your reaction time is on par with the time it takes for plastic to decompose.",
    "If you killed as much people as made excuses, you would've topped the scoreboard by now.",
    "I'm sure you exist only because the other sperm felt bad.",
    "Brains aren't everything. In your case, they aren't anything.",
    "I'm not going to fight you, I'd rather fight a punching bag than a trash bag.",
    "If you honestly call that trying, you're not even a candidate for the participation award.",
    "Even Jar-Jar Binks got a couple of kills...",
    "Do Irish guys pick you up and get really excited that they found a Potato?",
    "You know what might help lower your blood pressure? Slitting your wrists.",
    "Keep talking, maybe someday you'll say something intelligent!",
    "You know what they say, whatever doesn't kill you is just a surprise to the rest of us.",
    "You're the best at everything you do! Too bad all you do is disappoint.",
    "I appreciate you letting us win a few rounds to make it fair, but you can start trying now.",
    "Oh look, Hitler missed one",
    "Team Fortress 2 is also free to uninstall",
    "Did your parents ever ask you to run away from home?",
    "Your mom should've swallowed you",
    "Internet Explorer could run faster than you",
    "Does your brain run on Internet Explorer?",
    "I'd tell you to shoot yourself, but I bet you'd miss",
    "At least your ping score is higher than mine",
    "I would slap you, but that would be animal abuse",
    "I'd tell you to hit alt + f4 but you'd probably miss the keys",
    "What's higher, your IQ or your age?",
    "I'd say I fucked your Mom, but somebody already made that mistake ",
    "Your family tree must be a circle",
    "I didn't know the 'Make A Wish' foundation gave out copies of csgo.",
    "This isn't Pokemon, stop catching 'em all enemy bullets.",
    "My dead parents have a better K:D than you do",
    "At least your ping knows how to high score.",
    "Friendly fire was invented because of you",
    "Safest place for us to stand is in front of your gun",
    "Are you trying to beat the sea in a salt contest? That's probably the only thing you're winning right now.",
    "Get off your knees, you're blowing the game",
    "The only way you guys could let me down harder would be by pushing me into the grand canyon.",
    "I've seen people like you before, but I had to pay admission.",
    "Not even aimhack could increase your accuracy  ",
    "You seem to be a pacifist, because the healer has more kills than you.",
    "u must have been born on a highway because that's where most accidents happen.",
    "Why is it acceptable for you to be terrible, but not for me to point it out?",
]

const run = async () => {
    insults.map(submission => {
        submission = submission.trim()
        submitRequest({ submission })
    })
}

const submitRequest = (data) => {
    axios.post(Config.endpoint, data)
      .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });
}

run();